<?php
/**
 * CheckoutFormStatusTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\AllegroSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Allegro REST API
 *
 * https://developer.allegro.pl/about  Documentation is generated from [this](https://developer.allegro.pl/swagger.yaml) OpenAPI 3.0 specification file.
 *
 * The version of the OpenAPI document: latest
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\AllegroSDK\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CheckoutFormStatusTest Class Doc Comment
 *
 * @category    Class
 * @description Describes status of the form delivery and purchase options based on payment and purchase status. * &#x60;BOUGHT&#x60; - purchase without checkout form filled in * &#x60;FILLED_IN&#x60; - checkout form filled in but payment is not completed yet so data could still change * &#x60;READY_FOR_PROCESSING&#x60; - payment completed. Purchase is ready for processing. * &#x60;CANCELLED&#x60; - purchase cancelled by buyer.
 * @package     OpenAPI\AllegroSDK
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CheckoutFormStatusTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CheckoutFormStatus"
     */
    public function testCheckoutFormStatus()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
