<?php
/**
 * CompatibilityListSupportedCategoriesDtoSupportedCategoriesTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\AllegroSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Allegro REST API
 *
 * https://developer.allegro.pl/about  Documentation is generated from [this](https://developer.allegro.pl/swagger.yaml) OpenAPI 3.0 specification file.
 *
 * The version of the OpenAPI document: latest
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\AllegroSDK\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CompatibilityListSupportedCategoriesDtoSupportedCategoriesTest Class Doc Comment
 *
 * @category    Class
 * @description CompatibilityListSupportedCategoriesDtoSupportedCategories
 * @package     OpenAPI\AllegroSDK
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CompatibilityListSupportedCategoriesDtoSupportedCategoriesTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CompatibilityListSupportedCategoriesDtoSupportedCategories"
     */
    public function testCompatibilityListSupportedCategoriesDtoSupportedCategories()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "category_id"
     */
    public function testPropertyCategoryId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "items_type"
     */
    public function testPropertyItemsType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "input_type"
     */
    public function testPropertyInputType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "validation_rules"
     */
    public function testPropertyValidationRules()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
