<?php
/**
 * GetSaleProductsResponseTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\AllegroSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Allegro REST API
 *
 * https://developer.allegro.pl/about  Documentation is generated from [this](https://developer.allegro.pl/swagger.yaml) OpenAPI 3.0 specification file.
 *
 * The version of the OpenAPI document: latest
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\AllegroSDK\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * GetSaleProductsResponseTest Class Doc Comment
 *
 * @category    Class
 * @description GetSaleProductsResponse
 * @package     OpenAPI\AllegroSDK
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class GetSaleProductsResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GetSaleProductsResponse"
     */
    public function testGetSaleProductsResponse()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "products"
     */
    public function testPropertyProducts()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "categories"
     */
    public function testPropertyCategories()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "filters"
     */
    public function testPropertyFilters()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "next_page"
     */
    public function testPropertyNextPage()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
